name: Deploy to Elasticbeanstalk

on:
  push:
    paths:
      - "Section 6/workflow/**"
      - .github/workflows/deploy-eb-application.yml

env:
  REGISTRY: ${{ secrets.DOCKER_HUB_NAMESPACE }}

defaults:
  run:
    working-directory: "Section 6/workflow"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Build Frontend Application
        run: npm install
        working-directory: "Section 6/workflow/frontend"
      
      - name: Run Frontend Test Coverage
        run: npm run test -- --coverage
        working-directory: "Section 6/workflow/frontend"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}
          flavor: |
            prefix=workflow-frontend-
            suffix=-${{ matrix.node-version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "Section 6/workflow/frontend"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create docker-compose file
        uses: franzbischoff/replace_envs@v1
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          FRONT_END_IMAGE_TAG: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        with:
          from_file: 'Section 6/workflow/docker-compose.yaml'
          to_file: 'Section 6/workflow/docker-compose.yaml'
          commit: 'false'

      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yaml

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')"  

      - name: Deploy to AWS
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: workflow
          environment_name: Workflow-env
          version_label: workflow-frontend-${{ matrix.node-version }}-${{ steps.timestamp.outputs.date }}
          region: us-east-1
          deployment_package: "Section 6/workflow/deploy.zip"
